### ISSUE TITLE
Survey existing users

### ISSUE THREAD

**Issue by StevenMaude** [opensafely-core/codespaces-initiative#1]
## Goal
To be more confident that working on Codespaces is worthwhile and that we can add value.

We believe that running a survey with our existing users will help us to meet our goal. In particular it will help us to:
* better understand what problems they face at the moment with using OpenSAFELY locally
* validate the assumptions below
* create an accurate mental model of how our users work

## Assumptions

We currently assume that most of our existing users will:

* typically have a good quality internet connection while working on their code
* struggle with installing all of the dependencies required for OpenSAFELY, especially Python and Docker
* be comfortable using VSCode for writing ehrQL code, and potentially their analysis code
* be using a web browser that will be compatible with Codespaces, with no IT restrictions that would stop them using Codespaces.

## Tasks

- [x] Write and agree the questions for the survey (include Catherine)
- [x] Create the survey (Google Form - anonymous with option to give details) 
- [x] Run a pilot of the survey with a small number of users to confirm we've got the wording correct
- [x] Update the survey based on initial feedback
- [x] Send the survey out to all existing users
- [x] Encourage users to complete the survey (ask copilots to help, pop into the weekly/quarterly meetings)

## The survey details

Audience: anyone with ProjectDeveloper on any project.

Questions: see [this doc](https://docs.google.com/document/d/1tw46rI9ygoW7D7N3Z0xsX4WKt_hKz40r7KZTS2kALGA/edit#heading=h.1q59buwuh7fz).

## Summary and interpretation

These tasks are now covered by #32

**Comment by lucyb** [comment]
Catherine has agreed to help us out with creating some questions, so we could do a 3 amigos on this ticket next week.

**Comment by Jongmassey** [comment]
[GitHub docs for creating a direct codespaces link](https://docs.github.com/en/codespaces/setting-up-your-project-for-codespaces/setting-up-your-repository/facilitating-quick-creation-and-resumption-of-codespaces) could also be used for #2

**Comment by StevenMaude** [comment]
We've finalised the survey and are sending it out. We'll have to wait a few days for responses, send gentle reminders to try and get as many responses as possible, and then we'll review the results.

**Comment by lucyb** [comment]
Given that we've set a deadline of the end of today, I'm going to close this ticket, as I don't believe anything else needs to be done. We can continue to keep the survey open beyond the deadline just in case.
